### ISSUE TITLE
Why not mailing lists and patch sets?

### ISSUE THREAD

**Issue by prmadev** [0atman/markrequests#1]
Why not mailing lists and sending patch sets, in the style of Linux kernel development and SourceHut?

**Comment by Jak2k** [comment]
I think because mails are trash. There are neither encrypted nor modern. They are also complicated to set up, defend against spam and they are a hell to use.

**Comment by 0atman** [comment]
@prmadev we already have that, sourcehut is terrific if you'd like that.

As @Jak2k said, not having an external service (like mail) to store issues and PRS is going to be great. Everything is plain text, on your local machine, with only the git command and your editor required.
